[versions]
quarkus = "3.33.3.1"
delta = "4.0.1"
spark = "4.0.1"
hadoop = "3.4.2"
scala = "2.13.16"
jackson = "2.20.0"
httpclient = "5.5"
junit = "6.0.0"
assertj = "3.27.3"
mockito = "5.19.0"

[libraries]
delta-kernel-api = { module = "io.delta:delta-kernel-api", version.ref = "delta" }
delta-kernel-defaults = { module = "io.delta:delta-kernel-defaults", version.ref = "delta" }
delta-spark = { module = "io.delta:delta-spark_2.13", version.ref = "delta" }
spark-sql = { module = "org.apache.spark:spark-sql_2.13", version.ref = "spark" }
hadoop-common = { module = "org.apache.hadoop:hadoop-common", version.ref = "hadoop" }
scala-library = { module = "org.scala-lang:scala-library", version.ref = "scala" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
httpclient = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient" }
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[bundles]
testing = ["junit-jupiter", "assertj", "mockito"]
