livy.server.host = 0.0.0.0
livy.server.port = 8998
livy.spark.master = local[2]
livy.spark.deploy-mode = client
livy.file.local-dir-whitelist = /opt/fiq
livy.server.session.allow-custom-classpath = false
livy.server.recovery.mode = off
